[package]
name = "oasis-std"
version = "0.1.0"
license = "MIT/Apache-2.0"
description = "A standard library for interacting with the Oasis platform."
repository = "https://github.com/oasislabs/oasis-std.git"
authors = ["Oasis Labs <info@oasislabs.com>"]
edition = "2018"
readme = "README.md"
keywords = ["oasis", "owasm"]
categories = ["os", "wasm"]

[dependencies]
failure = "0.1"
fixed-hash = { version = "0.3", default-features = false }
serde = "1.0"
serde_derive = "1.0"
uint = { version = "0.6", default-features = false }

[workspace]
members = [".", "abi_derive", "abi_derive/tests"]

[features]
platform-alloc = []
